site_name: TXRX Doc Hub
site_url: https://niell-ion.github.io/RAR_Marmon_TXRX/
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - RAR:
      - Table of Contents: rar_toc.md
      - RAR: rar.md 
      - Preface: rarpreface.md
      - System Overview: raroverview.md
      - Operations: raroperations.md
      - Maintenance: rarmaintenance.md
      - Troubleshooting: rartroubleshooting.md
    - Switch Gap Detector:
      - Table of Contents: switchgaptoc.md
      - Preface: switchgappreface.md
      - System Overview: switchgapoverview.md
      - Operations: switchgapoperations.md
      - Maintenance: switchgapmaintenance.md
      - Troubleshooting: switchgaptroubleshooting.md
    - Portable Crossing Gate:
      - Table of Contents: crossing_toc.md
      - Preface: crossingpreface.md
      - System Overview: crossingoverview.md
      - Operations: crossingoperations.md
      - Maintenance: crossingmaintenance.md
      - Troubleshooting: crossingtroubleshooting.md
markdown_extensions:
  - attr_list:
  - toc:
      permalink: true
