site_name: TXRX Doc Hub
site_url: https://niell-ion.github.io/RAR_Marmon_TXRX/
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - RARs: rars.md 
markdown_extensions:
  - attr_list:
  - toc:
      permalink: true
