site_name: TXRX Doc Hub
site_url: https://niell-ion.github.io/RAR_Marmon_TXRX/
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - RAR: rar.md 
    - Switch Gap Detector: switchgap.md
    - Portable Crossing Guard: crossing.md
markdown_extensions:
  - attr_list:
  - toc:
      permalink: true
