site_name: TXRX Doc Hub
site_url: https://niell-ion.github.io/RAR_Marmon_TXRX/
theme:
  name: material
  palette: 
    primary: deep orange
    accent: blue
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - RAR:
      - Table of Contents: rar/rar_toc.md
      - Preface: rar_preface.md
      - System Overview: rar_overview.md
      - Operations: rar_operations.md
      - Maintenance: rar_maintenance.md
      - Troubleshooting: rar_troubleshooting.md
    - Switch Gap Detector:
      - Table of Contents: switchgap_toc.md
      - Preface: switchgap_preface.md
      - System Overview: switchgap_overview.md
      - Operations: switchgap_operations.md
      - Maintenance: switchgap_maintenance.md
      - Troubleshooting: switchgap_troubleshooting.md
    - Portable Crossing Gate:
      - Table of Contents: crossing_toc.md
      - Preface: crossing_preface.md
      - System Overview: crossing_overview.md
      - Operations: crossing_operations.md
      - Maintenance: crossing_maintenance.md
      - Troubleshooting: crossing_troubleshooting.md
markdown_extensions:
  - attr_list:
  - toc:
      permalink: true
